### ISSUE TITLE
Bag algorithm about filter

### ISSUE THREAD

**Issue by xuanzhaopeng** [cucumber/cucumber-ruby-core#97] opened 2015-12-11 18:18 UTC
Source:

https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/filters/locations_filter.rb#L15

Test case: 
If I will run 2400 features in CI, for each feature, It contains only 1 scenario outlines, and for each scenario outlines, which contains 10 tests

Thus, the 'locations' in filter(tag/name/location) will be 2400
Thus the 'test cases' in filter(tag/name/location) will be 2400 * 1 * 10 = 24000

so Cucumber-core will do (fake code)
for 1..2400
     for 1.. 24000
          do_match
     end
end 

Then the time complexity is O(K * N * N), 
N is the count of feature files included during execution
K is the average count of test case in each scenario outlines.

Then the time complexity could be => O(n * n)

I think we could improve this algorithm :)

If you don't have enough time, I could fix it :)

**Comment by brasmusson** [comment] 2015-12-12 10:22
This seems to be a duplicate of https://github.com/cucumber/cucumber-ruby/issues/901, with a potential fix in https://github.com/cucumber/cucumber-ruby-core/pull/96.

**Comment by xuanzhaopeng** [comment] 2015-12-16 09:13
Thanks a lot for quick response ! I

**Comment by mattwynne** [comment] 2015-12-17 13:02
Fixed in c5b9f0e48abaed940b72935c06d6603e1421a221

**Closed by mattwynne** 2015-12-17 13:02 UTC
